title: AskPdf # Your user_name
description: Chat with Pdf # Description text
show_downloads: true # Tells you download option of your page (tar| zip) format
# theme: jekyll-theme-minimal # here you can choose theme of your choices
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one